name: Deploy & configure Cloud Compute

on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'compute/**'
      - '.github/workflows/compute.yaml'
      - 'policies/**'

jobs:
  build:
    name: Setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: compute
    env:
      tf_actions_working_dir: compute
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Configure Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Terraform initialize
      - name: Terraform init
        working-directory: ${{ env.tf_actions_working_dir }}
        run: terraform init

      # Validate Terraform files
      - name: Validate Terraform files
        working-directory: ${{ env.tf_actions_working_dir }}
        run: |
          terraform validate

      # Run Terraform Plan
      - name: Terraform Plan
        working-directory: ${{ env.tf_actions_working_dir }}
        run: |
          terraform plan

      # Run Prisma Cloud Checkov to check for misconfigurations
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        env:
          PRISMA_API_URL: https://api.ca.prismacloud.io
        with:
          external_checks_dirs: policies/
          skip_check: CKV_AWS_50,CKV_AWS_116,CKV_AWS_116,CKV_AWS_117,CKV_AWS_272,CKV_AWS_115,CKV2_AWS_11
          api-key: ${{ secrets.BC_API_KEY }}

      # - name: Apply Terraform & save state
      #   working-directory: ${{ env.tf_actions_working_dir }}
      #   run: |
      #     terraform plan
      #     terraform apply -auto-approve

      # checkov -f tfplan.json --external-checks-dir ../policies -c CKV_AWS_666 