name: Deploy & configure Cloud Networking

on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'networking/**'
      - '.github/workflows/networking.yaml'

jobs:
  build:
    name: Setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: networking
    env:
      tf_actions_working_dir: networking
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Configure Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Terraform initialize
      - name: Terraform init
        working-directory: ${{ env.tf_actions_working_dir }}
        run: terraform init

      # Validate Terraform files
      - name: Validate Terraform files
        working-directory: ${{ env.tf_actions_working_dir }}
        run: |
          terraform validate

      # Run Terraform Plan
      - name: Terraform plan
        working-directory: ${{ env.tf_actions_working_dir }}
        run: |
          terraform plan

      # Run Prisma Cloud Checkov to check for misconfigurations
      - name: Prisma Cloud - Bridgecrew
        id: prisma-cloud
        uses: bridgecrewio/checkov-action@master
        env:
          PRISMA_API_URL: https://api.ca.prismacloud.io
        with:
          api-key: ${{ secrets.BC_API_KEY }}

      # - name: Run Terraform & save state
      #   working-directory: ${{ env.tf_actions_working_dir }}
      #   run: |
      #     terraform plan
      #     terraform apply -auto-approve